data_config:
    data_loc: "data"
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
    img_size: [256, 256]

train_parameters:
    models:
        baseline:
            lr: 0.00005
            epochs: 100
            batch_size: 32
                
    
test_parameters:
    models:
        baseline:
            batch_size: 32
    