data_config:
    data_loc: "data"
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    img_size: [256, 256]

train_parameters:
    models:
        baseline:
            lr: 0.00001
            epochs: 100
            batch_size: 8

        smallnet:
            lr: 0.00001
            epochs: 100
            batch_size: 16
                
    
test_parameters:
    models:
        baseline:
            batch_size: 8

        smallnet:
            batch_size: 16
    