data_config:
    data_loc: "data"
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    img_size: [256, 256]

train_parameters:
    models:
        baseline:
            lr: 0.00001
            epochs: 100
            batch_size: 8

        smallnet:
            lr: 0.01
            epochs: 100
            batch_size: 8


        smallnet2a:
            lr: 0.00001
            epochs: 200
            batch_size: 16

        smallnet2b:
            lr: 0.000001
            epochs: 200
            batch_size: 16

        smallnet2c:
            lr: 0.001
            epochs: 100
            batch_size: 8

        smallnet2d:
            lr: 0.001
            epochs: 100
            batch_size: 16

        mobilenet_pretrained:
            lr: 0.0001
            epochs: 100
            batch_size: 32

        segnet:
            lr: 0.00003
            epochs: 100
            batch_size: 16
        
        segnet_pretrained:
            lr: 0.03
            epochs: 100
            batch_size: 8

                
    
test_parameters:
    models:
        baseline:
            batch_size: 8

        mobilenet_pretrained:
            batch_size: 32

        smallnet:
            batch_size: 8

        smallnet2a:
            batch_size: 16

        smallnet2b:
            batch_size: 16

        smallnet2c:
            batch_size: 16

        smallnet2d:
            batch_size: 64

        segnet:
            batch_size: 16

        segnet_pretrained:
            batch_size: 8